### PR TITLE
Fixes #1 and #3

### LINKED ISSUE #1: TODO: write tests
I'll try to help you out with this soon.

### PR DESCRIPTION
**Pull request by alessioalex**
I wrote tests for almost everything (except createWriteStream since that will perhaps be deprecated in future levelUp versions), I discovered a bug in the process ( issue #3 ) and fixed it.

Let me know if this is ok and perhaps publish a new version of level-prefix to NPM.

### CODE REVIEW

**Comment by juliangruber** [comment]
fuck yeah!

**Comment by juliangruber** [comment]
I've also made you a collaborator of this repo :)

**Comment by alessioalex** [comment]
thanks man! I'll be working on adding batch and createValueStream / createKeyStream next.

**Comment by juliangruber** [comment]
released as `0.0.1`

**Pull request merged**
